name: Deploy Frontend to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Create .env.production
        run: echo "VITE_API_BASE_URL=https://${{ vars.BACKEND_DOMAIN }}" > .env.production

      - name: Build Project
        run: pnpm run build

      - name: Zip the build directory
        run: zip -r dist.zip dist

      - name: Transfer Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.FRONTEND_DOMAIN }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist.zip"
          target: "~/"

      - name: Unzip and Move Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.FRONTEND_DOMAIN }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            unzip ~/dist.zip && sudo rm -rf ~/stack/nginx/html &&
            sudo mv ~/dist ~/stack/nginx/html && rm ~/dist.zip
